export enum BookingStatus {
  INITIATED = 'INITIATED',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PENDING_GROUP_PAYMENT = 'PENDING_GROUP_PAYMENT',
  CONFIRMED = 'CONFIRMED',
  CHECKED_IN = 'CHECKED_IN',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum BookingType {
  TICKET = 'ticket',
  TABLE = 'table',
  APARTMENT = 'apartment',
  CAR = 'car',
}

export enum PaymentStatus {
  UNPAID = 'UNPAID',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  FULLY_PAID = 'FULLY_PAID',
  REFUNDED = 'REFUNDED',
}

export enum TableCategory {
  STANDARD = 'standard',
  VIP = 'vip',
  VVIP = 'vvip',
  BOOTH = 'booth',
  PRIVATE = 'private',
}

export enum OrderStatus {
  CREATED = 'CREATED',
  ASSIGNED = 'ASSIGNED',
  ROUTED = 'ROUTED',
  IN_PREPARATION = 'IN_PREPARATION',
  READY = 'READY',
  SERVED = 'SERVED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum UserRole {
  CUSTOMER = 'customer',
  WAITER = 'waiter',
  KITCHEN_STAFF = 'kitchen_staff',
  BAR_STAFF = 'bar_staff',
  DOOR_STAFF = 'door_staff',
  MANAGER = 'manager',
  ADMIN = 'admin',
  SUPER_ADMIN = 'super_admin',
}

// ← NEW
export enum BusinessScope {
  CAR_RENTAL = 'CAR_RENTAL',
  APARTMENT = 'APARTMENT',
  TABLE_CLUB = 'TABLE_CLUB',
  EVENT_TICKETING = 'EVENT_TICKETING',
}

export enum AuditActionType {
  BOOKING_CREATED = 'BOOKING_CREATED',
  BOOKING_UPDATED = 'BOOKING_UPDATED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  BOOKING_EXPIRED = 'BOOKING_EXPIRED',
  BOOKING_CHECKED_IN = 'BOOKING_CHECKED_IN',
  PAYMENT_PROCESSED = 'PAYMENT_PROCESSED',
  PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_ASSIGNED = 'ORDER_ASSIGNED',
  ORDER_COMPLETED = 'ORDER_COMPLETED',
  ADMIN_OVERRIDE = 'ADMIN_OVERRIDE',
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  TICKET_SCANNED = 'TICKET_SCANNED',
  STAFF_DEACTIVATED = 'STAFF_DEACTIVATED',       // ← NEW
  STAFF_SCOPE_UPDATED = 'STAFF_SCOPE_UPDATED',   // ← NEW
  SETTINGS_UPDATED = 'SETTINGS_UPDATED',         // ← NEW
  CAMPAIGN_SENT = 'CAMPAIGN_SENT',               // ← NEW
  CAMPAIGN_FEE_CHARGED = 'CAMPAIGN_FEE_CHARGED', // ← NEW
  INVENTORY_RESTOCKED = 'INVENTORY_RESTOCKED',   // ← NEW
  INVENTORY_DEDUCTED = 'INVENTORY_DEDUCTED',     // ← NEW
  INVENTORY_ITEM_CREATED = 'INVENTORY_ITEM_CREATED', // ← NEW
  REFUND_INITIATED = 'REFUND_INITIATED',         // ← NEW
  WALLET_CREDITED = 'WALLET_CREDITED',           // ← NEW
  QUEUE_ADVANCED = 'QUEUE_ADVANCED',             // ← NEW
  QUEUE_CLOSED = 'QUEUE_CLOSED',                 // ← NEW
  CAUTION_FEE_REFUNDED = 'CAUTION_FEE_REFUNDED', // ← NEW
  CAUTION_FEE_FORFEITED = 'CAUTION_FEE_FORFEITED', // ← NEW
  PRICE_UPDATED = 'PRICE_UPDATED',               // ← NEW
}